---
- name: Push config file
  template:
    dest: "/etc/gitea/app.ini"
    src: "app.ini"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: "0600"

- name: Generate secrets 
  shell: "/opt/gitea/gitea generate secret {{item}}"
  loop:
    - "INTERNAL_TOKEN"
    - "JWT_SECRET"
    - "SECRET_KEY"